###############################################################################
# Automator configuration file
###############################################################################

#user info should be put in on the cmd line

#optional arguments are commented out which you can override
#project: cidc-biofx #default: cidc-biofx
#zone: us-east1-b #default: us-east1-b

instance:
  name: wes-auto-test # UNIQUE name for instance
  image_family: wes #default: wes
  #commit_string: #default: None--which checks out master branch
  #machine_type: n1-highmem-96 #mchine to run the pipeline
  #serviceAcct:  biofxvm@cidc-biofx.iam.gserviceaccount.com 

disk:
  name: wes-auto-test-disk # UNIQUE name for disk
  size: "10" #in GB

#define the samples as in config.yaml but with google bucket paths
samples:
  CA209009-Normal:
    - gs://lens_bucket2/wes/wes_testset/data/CA209009.N.1.fq.gz
    - gs://lens_bucket2/wes/wes_testset/data/CA209009.N.2.fq.gz
  CA209009-Tumor:
    - gs://lens_bucket2/wes/wes_testset/data/CA209009.T.1.fq.gz
    - gs://lens_bucket2/wes/wes_testset/data/CA209009.T.2.fq.gz

metasheet:
  #Define the metasheet, give the name of the run, and then list NORMAL first
  #tumor second
  - CA209009_run:
    - CA209009-Normal
    - CA209009-Tumor
#  - run2:
#    - sample2_normal
#    - sample2_tumor

