# Give the new instance a unique name, e.g. the wes run name
# NOTE: "wes-auto" will automatically be prepended to this string
instance_name: "test1"

# Define the number of cores for the wes instance
# Options- 32 (default), 64, 96 
cores: 32

# Define the disk size to use in GB, default 500
# the name of the persistent disk will be: "wes_auto_{instance_name}_disk"
disk_size: 50

#DEFINE the path to the google bucket path for the run
google_bucket_path: gs://lens_bucket2/wes_automator/test1/

# Uncomment the following and define the specific wes commit string to use
# wes_commit: 44b17ff
wes_commit: new_germline

# DEFINE the samples- each sample should have a name, e.g. SAMPLE1
# and a Google bucket path to the input file, 
# e.g. gs://mybucket/data/sample1.fastq.gz
# VALID INPUTS: fastq, fastq.gz
# NOTE: for PAIRED-END fastq/fastq.gz, give both pairs to the sample:
# SAMPLE_1_PE:
#   - gs://mybucket/data/sample1_pair1.fastq
#   - gs://mybucket/data/sample1_pair2.fastq
samples:
  CA209009-Normal:
    - gs://lens_bucket2/wes_remotes/len/data/CA209009.N.1.fq.gz
    - gs://lens_bucket2/wes_remotes/len/data/CA209009.N.2.fq.gz
  CA209009-Tumor:
    - gs://lens_bucket2/wes_remotes/len/data/CA209009.T.1.fq.gz
    - gs://lens_bucket2/wes_remotes/len/data/CA209009.T.2.fq.gz

# metahseet- Group the samples into Tumor/Normal "runs"
# each run should have a name, e.g. run_1:
# then under each run, define a tumor and a normal sample
# EXAMPLE:
# metasheet:
#  run_1:
#    tumor: SAMPLE_Tumor
#    normal: SAMPLE_normal
metasheet:
  CA209009_Run:
    tumor: CA209009-Tumor
    normal: CA209009-Normal


